### ISSUE TITLE
[Feature Request] Option to disable account creation.

### ISSUE THREAD

**Issue by perronedotdev** [andrii-kryvoviaz/slink#10]
I know that we can set it to where we have to verify users that sign up, but I'd like to be able to just disable registrations all together. I've created my account and won't need anyone else to make accounts.

**Comment by andrii-kryvoviaz** [comment]
Yeah, I thought about that. Will add it as another configuration flag.

In such case, maybe another CLI command would be helpful to create the initial user account. Or a web form, on the first start up.

**Comment by perronedotdev** [comment]
A simple web form to create an admin account would be perfect.

**Comment by Tiritibambix** [comment]
Yes, I am looking forward to this :)
