### ISSUE TITLE
Feature Request: ICO File Support

### ISSUE THREAD

**Issue by PastaGringo** [andrii-kryvoviaz/slink#2]
Hi,

Project is amazing, everything is perfect.
Can't wait to have the admin panel 🙏.

Just one question, why is it not allowed to upload .ico file?

I modified the line about mime types to include ico files (and restarted the container) but it's still not allowed:

`
#[Assert\Image(maxSize: '5M', mimeTypes: ['image/png', 'image/jpeg', 'image/jpg', 'image/gif', 'image/webp', 'image/svg+xml', 'image/svg', 'image/ico'])]
`

Any reason to not support ICO file?
Thanks

**Comment by PastaGringo** [comment]
The mimeTypes was wrong. 
I updated the code by:

`#[Assert\Image(maxSize: '5M', mimeTypes: ['image/png', 'image/jpeg', 'image/jpg', 'image/gif', 'image/webp', 'image/svg+xml', 'image/svg', 'image/x-icon', 'image/vnd.microsoft.icon'])]`

And slink is now able to serve ICO files ⚡

Any plan to support it?

**Comment by andrii-kryvoviaz** [comment]
Great addition! I just completely forgot about `.ico` files.
I intend to add support in the nearest build. Thanks.

**Comment by PastaGringo** [comment]
Awesome! 🚀
Thanks

**Comment by andrii-kryvoviaz** [comment]
ICO file support has been added in 19e3c3f.
You can now try a new pre-release with this feature [v1.0.0-rc.7](https://github.com/andrii-kryvoviaz/slink/releases/tag/v1.0.0-rc.7)  🎉

If you have `watchover` installed, it should pick it up by the `latest` tag.
