### ISSUE TITLE
Account Verification

### ISSUE THREAD

**Issue by PitchAbyss** [andrii-kryvoviaz/slink#24]
Usually how long does it takes to verify the account , i dont understand if its self hosted why are we blocked to account creation

![image](https://github.com/andrii-kryvoviaz/slink/assets/13099434/42650ad4-53e2-4066-a711-b82ac5cf717a)

**Comment by thegabriele97** [comment]
If I remember correctly you need to enable your account using the CLI util

**Comment by andrii-kryvoviaz** [comment]
Some people may open it for public access, so it has to be protected.

To verify your account just simply run:
```bash
docker exec -it slink slink user:activate --email=<user-email>
```

or alternatively you can disable account verification watsoever by passing `USER_APPROVAL_REQUIRED` environment variable into your containter and setting it to `false`.

User verification is enabled by default, for the reason I have described above. Later, Slink will have a setup wizard to make the first installation more explicit.

**Comment by iamLazyCode** [comment]
> Some people may open it for public access, so it has to be protected.
> 
> To verify your account just simply run:
> ```bash
> docker exec -it slink slink user:activate --email=<user-email>
> ```
> 
> or alternatively you can disable account verification watsoever by passing `USER_APPROVAL_REQUIRED` environment variable into your containter and setting it to `false`.
> 
> User verification is enabled by default, for the reason I have described above. Later, Slink will have a setup wizard to make the first installation more explicit.

Thankyou so much for the prompt response and solution i look forward to this project have set high hopes being clean and light weight

I am yet to enter ui does this project have folder option too to keep things organized

**Comment by andrii-kryvoviaz** [comment]
I am planning to introduce some kind of grouping in the future, but that won't affect underlying folder structure. Will be just another ui improvement.

**Comment by iamLazyCode** [comment]
> I am planning to introduce some kind of grouping in the future, but that won't affect underlying folder structure. Will be just another ui improvement.

I hope it can be something related to folder categories  but thanks alot for this beautiful project
