### ISSUE TITLE
[Improvement]: Incorrect label at sign-in

### ISSUE THREAD

**Issue by Aetherinox** [andrii-kryvoviaz/slink#27]
I'm not sure if there's a plan to allow username OR email sign-in, but at present on the sign-in page, it asks for the username, but wants the email address. Sort of makes it confusing.

![lXY0mcCqis](https://github.com/user-attachments/assets/efbbe1f2-4c7e-4d02-8cbb-722453961d87)

(FYI, I did try a valid username the first time).

**Comment by andrii-kryvoviaz** [comment]
It’s not exactly a bug, but more of a wording issue. You’re correct that it could be misleading. I’ll consider making it more explicit. Thanks.

**Comment by andrii-kryvoviaz** [comment]
Starting from [`v1.2.0`](https://github.com/andrii-kryvoviaz/slink/releases/tag/v1.2.0)  there is a possibility to login either with email or username. For already existing users it has been automatically generated based on the display name and could be found under profile settings.

**Comment by Aetherinox** [comment]
Sweet. Thanks. Makes it easier.
