### ISSUE TITLE
[ Feature Request ] Show thumbnails of the uploads in upload history page

### ISSUE THREAD

**Issue by arpanghosh8453** [andrii-kryvoviaz/slink#3]
First of all, I just found this from the selfh.st page, and it looks so modern and sleek, wanted to give it a try. I absolutely love the interface and available login option. The planned features makes it a real nice alternative to imgur.com. 

Currently it looks like this, where you can't locate the image you want to modify. Can you integrate a thumbnail of the image beside the name link? 

![image](https://github.com/andrii-kryvoviaz/slink/assets/26424944/ed445a4c-564d-4186-926c-316788ede425)

Also, is there a possibility to have grid view of uploads instead of list? I think that is a waste of space if there are many images. Can it be like the explore page style please?

**Comment by andrii-kryvoviaz** [comment]
Actually, I though about it as well. As, you can see, now it looks pretty simple. On the next iteration I was going to rework this page. Maybe to introduce two options for `grid view` and `list view` with bigger thumbnails and more metadata as opposed to the first one.

**Comment by arpanghosh8453** [comment]
That will be amazing actually. Thank you so much :)

**Comment by andrii-kryvoviaz** [comment]
It is now a part of [v1.0.0-rc.10](https://github.com/andrii-kryvoviaz/slink/releases/tag/v1.0.0-rc.10) pre-release 🎉
So, you can try it.

Here is a small sneak peek of how it looks now:
<img width="841" alt="image" src="https://github.com/andrii-kryvoviaz/slink/assets/12681464/91e13bee-55a1-454e-a637-f07c9c5e0c38">

It seems more informative this time, and it had to be this way from the beginning. But, anyway, I'm still thinking of `grid view` and whether it would be useful for this case, or just a simple listing is enough.

**Comment by arpanghosh8453** [comment]
I think a paginated setup with a sorting option will be cool if the grid view limits the options. Or you can have a grid view and reveal the options once selected. The implementation is up to you. This looks superb already!
