### ISSUE TITLE
[ Feature Request ] Add ability to delete uploaded images from upload history

### ISSUE THREAD

**Issue by arpanghosh8453** [andrii-kryvoviaz/slink#4]
Currently there is no option to remove an uploaded image from the UI. I think this is an essential feature for management.

**Comment by andrii-kryvoviaz** [comment]
Agree, that feature is missing. How I actually see it, it can be removed from the database, preserving the actual image on the disk, or removed from both placed. Thre should be a choice.

**Comment by andrii-kryvoviaz** [comment]
Slink [v1.0.0-rc.9](https://github.com/andrii-kryvoviaz/slink/releases/tag/v1.0.0-rc.9) now supports image deletion on the detailed information page:
<img width="997" alt="image" src="https://github.com/andrii-kryvoviaz/slink/assets/12681464/d6b39dd0-0852-4cae-9b0e-5be8ae03bad1">

This will come to upload history page (at least for list view), when I get to redo its layout as mentioned here #3.
Stay tuned :)

**Comment by arpanghosh8453** [comment]
Thank you, I will be waiting :). The interface looks fantastic.
