### ISSUE TITLE
[ Feature Request ] Show the added description to the public shared link

### ISSUE THREAD

**Issue by arpanghosh8453** [andrii-kryvoviaz/slink#5]
The added description does not show up anywhere, so I was wondering what is the use case for that. Is there any chance to add that to the public shared link page?

**Comment by andrii-kryvoviaz** [comment]
It should be displayed on the public page, if shared. 

I'm still thinking of the use case of it. My initial idea was to create some sort of short notes for an image, which could be used for personal use, or be shared, so others could get a hint.

**Comment by arpanghosh8453** [comment]
I did not see the description on the shared page, even though I added it later to the image. BTW, in the current version, once you add a description, you cannot remove it anymore. You must add something to replace it there.

**Comment by andrii-kryvoviaz** [comment]
Yes, it has validation applied, so an empty string won't work :)
I will add and extra API enpoint to clear the description.

**Comment by andrii-kryvoviaz** [comment]
I tied to set a description, for me it worked indeed.
<img width="1527" alt="image" src="https://github.com/andrii-kryvoviaz/slink/assets/12681464/8d9ba386-a312-4baf-ac6e-4ca9742b01b0">

Not sure, why it might not work for you. Will take a look at it later.

**Comment by arpanghosh8453** [comment]
I mean, not on the public discover page, I was referring to the link we get to share individual image.

**Comment by andrii-kryvoviaz** [comment]
Yep, they are just raw images ready to be embedded as is. 

As I see it now, there should be a completely different process for sharing, which will lead to the info page with limited permissions, lets say only to read. So, a user can decide what to share for each use case.

**Comment by arpanghosh8453** [comment]
I see, that makes sense. Maybe you can give two different URLs for different purposes.

**Comment by andrii-kryvoviaz** [comment]
Closely related to #7 as a part of an advanced image sharing strategy.
