### ISSUE TITLE
Unable to create an account on the first attempt

### ISSUE THREAD

**Issue by Tataukee** [andrii-kryvoviaz/slink#8]
Something went wrong please try later ... This is the message I receive when I attempt to create an account after freshly installed .

**Comment by andrii-kryvoviaz** [comment]
It was an infrastructure issue and has been fixed in [v1.0.0-rc.8](https://github.com/andrii-kryvoviaz/slink/releases/tag/v1.0.0-rc.8).

**Comment by nothing2obvi** [comment]
I can't see what version I'm using, but just spun this up today using "latest" and I can't create an account either. I press "Sign Up" but nothing happens. I tried this at the local address (http://10.0.0.224:3000) and the reverse proxied address (https://slink.mydomain.com).

**Comment by andrii-kryvoviaz** [comment]
@nothing2obvi make sure that you add `ORIGIN=https://slink.mydomain.com` environment variable to your docker container. Let me know if the issue still persists after you set it up.

**Comment by nothing2obvi** [comment]
Ahh, got it. I didn't include the subdomain on my first attempt. Thank you.
